version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  no-unused-vars:
    enabled: true
  naming:
    enabled: true

plugins:
  duplication:
    enabled: true
  structure:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
  markdownlint:
    enabled: true
    channel: "markdownlint-0-12-0"
  rubocop:
    enabled: true
    channel: "rubocop-1-31-0"
    issue_override:
      severity: critical
  flog:
    enabled: true
    config:
      score_threshold: 1.0

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
