version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic: DOING ACCEPTANCE ON QUA-865 -> REMOVE
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:DOING ACCEPTANCE ON QUA-865 -> REMOVE
      threshold: 4DOING ACCEPTANCE ON QUA-865 -> REMOVE
  return-statements:DOING ACCEPTANCE ON QUA-865 -> REMOVE
    enabled: trueDOING ACCEPTANCE ON QUA-865 -> REMOVE
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  no-unused-vars:
    enabled: true

plugins:
  duplication:
    enabled: false
  structure:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-7"
  rubocop:
    enabled: true
    channel: beta
    issue_override:
      severity: critical

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
