version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          DATABASE_URL: postgres://postgres@127.0.0.1:5432/wbooks-api_test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: react_rails_start_test
          POSTGRES_PASSWORD: postgres
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install --jobs 8
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load --trace
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests (and upload to local)
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec spec
            ./cc-test-reporter after-build --id 238109555c526749baac198ff41e26a643a0cea66f11d3667cfe405662bf692a -e https://edbe-2800-40-2a-934-d55a-35e2-a28d-b3d1.ngrok-free.app/v1/test_reports -d
      - run:
          name: Run tests (and upload to prod)
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec spec
            ./cc-test-reporter after-build --id 238109555c526749baac198ff41e26a643a0cea66f11d3667cfe405662bf692a
